services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billing_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      SECRET_KEY: "change-this-to-a-random-long-string"
      DATABASE_URL: "postgresql+psycopg://postgres:postgres@db:5432/billing_db"
      INVOICE_PDF_DIR: "/app/generated_invoices"
      BACKEND_CORS_ORIGINS: '["http://localhost:5173","http://localhost:3000"]'
    volumes:
      - ./generated_invoices:/app/generated_invoices
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ""
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:

